# config.yaml

# --- Configurações de Entrada ---
prisma_channels: 230
prisma_height: 3
prisma_width: 3

sentinel2_channels: 12
sentinel2_height: 7
sentinel2_width: 7

airbone_hyper_channels: 430
airbone_hyper_height: 19
airbone_hyper_width: 19

# --- Parâmetros da Arquitetura ---
tamanho_embedding: 128
num_prototipos: 32
num_heads: 2
num_layers: 2
dropout: 0.1

# --- Parâmetros MSN (EMA - Exponential Moving Average) ---
alpha_ema: 0.1         # Fator para atualização do modelo alvo (momentum)

# --- Parâmetros da Função de Perda MSN ---
temp_anchor: 0.1        # Temperatura para Softmax do estudante (anchor)
temp_target: 0.095      # Temperatura para Softmax/Sinkhorn do alvo (target)
lambda_reg: 0.5         # Peso para o termo de regularização ME-MAX
use_sinkhorn: True    # Se true, aplica Sinkhorn-Knopp nos alvos

# --- Parâmetros de Treinamento ---
learning_rate: 0.001
batch_size: 938
num_epochs: 50
num_anchor_views: 1     # Prisma e Sentinel2 são as visões estudante
weight_decay: 0.0001
label_smoothing: 0.0

warmup_epochs: 10          # Ex: 1 época de aquecimento (pode ajustar)
final_lr: 0.0             # Taxa de aprendizado final para o cosine decay (pode ser 0)
final_weight_decay: 0.4   # Weight decay final para o cosine decay (pode ajustar)


epoch_stop_prototype: 20

data_root: './../normalized_data/train'


# --- Configurações de Checkpoint ---
output_dir: './outputs'     # Diretório para salvar os modelos
save_freq_epochs: 100               # Frequência (em épocas) para salvar um checkpoint periódico

# Caminho para um checkpoint para continuar o treinamento.
# './outputs/proto32_embed256/min_loss_checkpoint.pth'
resume_from: null